### ISSUE TITLE
[feature req] implement method Close

### ISSUE THREAD

**Issue by Varunram** [hsanjuan/go-libp2p-gorpc#11]
in `net/rpc`, we have method Close() in type Client. Wold be nice to have it here, if possible, thanks!

**Comment by lanzafame** [comment]
@Varunram The `Client.Close()` method is primarily for closing the underlying codec in the `net/rpc` pkg, see [here](https://golang.org/src/net/rpc/client.go?s=7509:7544#L269) and [here](https://golang.org/src/net/rpc/client.go?s=6088:6128#L205). As this pkg doesn't have an underlying codec that requires closing a `Close` method is redundant.

**Comment by Varunram** [comment]
Oh, it makes sense now, thanks a ton!

**Comment by hsanjuan** [comment]
Perhaps we could provide a `Close` method that de-registers the protocol handler from the host in the `Server`, but you can achieve that with `host.RemoveStreamHandler(pid protocol.ID)` using the same protocol.ID and host used when creating the `Server`.

But in the case of the client, we have nothing to Close, other than the host itself.
