### ISSUE TITLE
[question] equivalent of net's Server.ServeConn()

### ISSUE THREAD

**Issue by Varunram** [hsanjuan/go-libp2p-gorpc#12]
I don't see a method that implements this - what we have is the ability to create a client and connect to a server instance, but there seems to be no method which addresses the setting up of the server that we want to connect to.

**Comment by Varunram** [comment]
@lanzafame thanks for the reply and the pointer. But in the example, we create a server and pass it on to a local client ; what if I have a node and I want it to act as a server for other nodes that will be communicating to the main node via RPC? The way I do it right now is I `serveConn` on the main node and then serve it via websockets. And then I simply connect to this websockets url on the nodes that I want to connect to. Can I do something similar with libp2p? (like have other nodes connect to me given my public key and where i have an RPC for it?) Thanks!

**Comment by lanzafame** [comment]
@Varunram All you need to do is provide the `peer.ID` of the `host.Host` that you use when creating the Server to the clients and use that as the `dest` parameter in the `client.Call` function. How you communicate that `peer.ID` to new clients is not something that this package provides but is very specific to what you want to accomplish. Hopefully, this helps 👍

**Comment by Varunram** [comment]
@lanzafame Thanks for helping me out with this! I think it makes sense now, I can get the peers to dial to one another, but I'm getting a few `connection refused` messages. Pretty sure that's related to how I handle stuff in my code rather than the library. Thanks again!
